<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>bae32ce4-5d4f-46fd-93dc-60c033a60944</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkillIssue.GG.Analysis\SkillIssue.GG.Analysis.csproj" />
    <ProjectReference Include="..\SkillIssue.GG.Application\SkillIssue.GG.Application.csproj" />
    <ProjectReference Include="..\SkillIssue.GG.Infrastructure\SkillIssue.GG.Infrastructure.csproj" />
  </ItemGroup>

</Project>
