name: SkillIssue.GG CI

on:
  push:
    branches:
      - main
      - development

  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore SkillIssue.GG.slnx

      - name: Build solution
        run: dotnet build SkillIssue.GG.slnx --no-restore --configuration Release

      - name: Run tests
        run: dotnet test SkillIssue.GG.slnx --no-build --configuration Release